theme: minima
title: GitHub page title
author: Felix Tse
email: felix@here.com
description: > # this means to ignore newlines until "baseurl:"
  Home page for the GitHub page

# social links
#twitter_username: your-twitter-handle
github_username:  felixtsem5

show_excerpts: true # set to false to remove excerpts on the homepage
